default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  encoding: unicode
  pool: 5
  username: lithium
  password:

development:
  <<: *default
  database: "foodswatch-development"

test:
  <<: *default
  database: "foodswatch-test"
